import "../app/_styles/globals.css";
import Header from "../app/_components/header.js";
import Footer from "../app/_components/footer.js";
import { AuthProvider } from "./context/AuthContext"; // import AuthContext
export const metadata = {
  title: "bd-tours",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-primary-950 text-primary-100 min-h-screen flex flex-col relative">
        <AuthProvider>
          <Header />

          <div className="flex-1 px-8 py-12 grid">
            <main>{children}</main>
          </div>

          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
